### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by metaphori**
* Correct paths for build/test in Windows envs

### CODE REVIEW

**Comment by metaphori** [comment]
```
14:55:09.533 [DEBUG] [TestEventLogger] it.unibo.protelis2kotlin.Protelis2KotlinTests > Generation of Kotlin interfaces from Protelis sources should work FAILED
14:55:09.533 [DEBUG] [TestEventLogger]     org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\travis\AppData\Local\Temp\junit3088809582474471322 with arguments [generateKotlinFromProtelis, dokka]
14:55:09.533 [DEBUG] [TestEventLogger] 
14:55:09.533 [DEBUG] [TestEventLogger]     Output:
14:55:09.533 [DEBUG] [TestEventLogger]     > Task :generateKotlinFromProtelis FAILED
14:55:09.533 [DEBUG] [TestEventLogger] 
14:55:09.533 [DEBUG] [TestEventLogger]     FAILURE: Build failed with an exception.
14:55:09.534 [DEBUG] [TestEventLogger] 
14:55:09.534 [DEBUG] [TestEventLogger]     * What went wrong:
14:55:09.534 [DEBUG] [TestEventLogger]     Execution failed for task ':generateKotlinFromProtelis'.
14:55:09.534 [DEBUG] [TestEventLogger]     > Failed to create MD5 hash for file content.
```

**Comment by DanySK** [comment]
Can you use the debugger and locate the exact line of code that's giving us headaches? Maybe we can work that around somehow

**Comment by metaphori** [comment]
@DanySK Despite the merging of the two plugins into one, there is still the following problem on Windows:

```
Execution failed for task ':generateKotlinFromProtelis'.
11:13:53.221 [DEBUG] [TestEventLogger]     > Failed to create MD5 hash for file content.
```

**Comment by metaphori** [comment]
This fixed #22

**Pull request merged**
